import PublicSiteShell, { PublicHero } from '@/components/PublicSiteShell';

const faqs = [
  ['Who is ApolloEMS designed for?','ApolloEMS is designed for EMS organizations that want to bring workforce, administrative, operational, dispatch, field, and clinical workflows into a more connected environment. The platform can support agencies with lean management teams as well as larger organizations seeking better visibility and fewer disconnected systems.'],
  ['Is ApolloEMS available now?','Yes. The core ApolloEMS platform is operational and available for agency implementation. Contact us to discuss your agency, the capabilities you need, and onboarding.'],
  ['Is the ePCR generally available?','Apollo ePCR is currently in private beta and is coming soon as the clinical documentation component of the ApolloEMS platform. Its current external beta environment is focused on EMS education and simulated patient care documentation while development continues.'],
  ['Can agencies choose modules?','Yes. ApolloEMS is designed as a modular platform so an agency can implement the capabilities that fit its operation. Module selection and configuration can be established during onboarding.'],
  ['Does ApolloEMS replace every system an agency uses?','ApolloEMS is designed to consolidate many of the workforce, administrative, operational, dispatch, field, and clinical workflows that are commonly spread across separate systems. The right implementation depends on each agency’s existing technology, requirements, and selected ApolloEMS modules.'],
  ['Is ApolloEMS only for smaller EMS agencies?','No. ApolloEMS is designed for EMS organizations of different sizes. Smaller agencies can benefit significantly from consolidating work when management resources are stretched thin, while larger organizations can benefit from connected workflows, shared operational visibility, and centralized management across more people and resources.'],
  ['Why was ApolloEMS built specifically for EMS?','EMS operations combine 24/7 staffing, credentials, vehicles, equipment, field crews, supervisors, dispatch activity, compliance, and clinical documentation in ways generic business software often does not reflect. ApolloEMS was conceived and built by a working EMS professional with nearly two decades of experience to address those realities directly.'],
];

export default function FAQPage() {
  return <PublicSiteShell><PublicHero eyebrow="Questions & Answers" title="ApolloEMS FAQ" description="Straightforward answers about the platform, availability, modules, and where ApolloEMS is headed."/><main className="px-5 py-16"><div className="mx-auto max-w-4xl space-y-4">{faqs.map(([q,a],i)=><details key={q} open={i<2} className="group rounded-2xl border border-slate-200 bg-white shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 p-6 text-lg font-black [&::-webkit-details-marker]:hidden"><span>{q}</span><span className="text-2xl font-light text-blue-700 transition group-open:rotate-45">+</span></summary><div className="border-t border-slate-100 px-6 pb-6 pt-5 text-base leading-7 text-slate-600">{a}</div></details>)}</div></main></PublicSiteShell>;
}
