'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import type { AgencyRecord } from '@/lib/adminAgencies';

export default function AgencyList() {
  const [agencies, setAgencies] = useState<AgencyRecord[]>([]), [search, setSearch] = useState(''), [status, setStatus] = useState('ALL'), [error, setError] = useState(''), [loading, setLoading] = useState(true);
  useEffect(() => { fetch('/api/admin/agencies').then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); setAgencies(result.agencies); }).catch((reason) => setError(reason.message)).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => agencies.filter((agency) => (status === 'ALL' || agency.status === status) && `${agency.name} ${agency.slug} ${agency.primary_contact_name}`.toLowerCase().includes(search.toLowerCase())), [agencies, search, status]);
  if (loading) return <div className="rounded-3xl bg-white p-8 shadow-sm">Loading agency registry…</div>;
  if (error) return <div className="rounded-3xl border border-amber-300 bg-amber-50 p-6"><h2 className="font-black text-amber-950">Agency registry setup required</h2><p className="mt-2 text-amber-900">{error}</p></div>;
  return <><div className="grid gap-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-[1fr_220px]"><input aria-label="Search agencies" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search name, slug, or contact" className="rounded-xl border border-slate-300 px-4 py-3" /><select aria-label="Filter by status" value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-xl border border-slate-300 px-4 py-3"><option value="ALL">All statuses</option>{['ONBOARDING','ACTIVE','SUSPENDED','INACTIVE'].map((value) => <option key={value}>{value}</option>)}</select></div>
  <div className="mt-6 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="grid grid-cols-[1fr_auto] gap-4 border-b border-slate-200 px-6 py-4 text-sm font-bold text-slate-500"><span>{filtered.length} {filtered.length === 1 ? 'agency' : 'agencies'}</span><span>{agencies.filter((a) => a.status === 'ACTIVE').length} active</span></div>{filtered.map((agency) => <Link key={agency.id} href={`/admin/agencies/${agency.id}`} className="grid gap-4 border-b border-slate-100 px-6 py-5 last:border-0 hover:bg-slate-50 md:grid-cols-[1.5fr_1fr_1fr_auto]"><div><p className="font-black">{agency.name}</p><p className="mt-1 text-sm text-slate-500">/{agency.slug}</p></div><div><p className="text-xs font-bold uppercase text-slate-400">Contact</p><p className="mt-1 font-semibold">{agency.primary_contact_name}</p></div><div><p className="text-xs font-bold uppercase text-slate-400">Modules</p><p className="mt-1 font-semibold">{agency.enabled_modules.length}</p></div><span className={`self-center rounded-full px-3 py-1 text-xs font-black ${agency.status === 'ACTIVE' ? 'bg-emerald-100 text-emerald-800' : agency.status === 'SUSPENDED' ? 'bg-red-100 text-red-800' : 'bg-amber-100 text-amber-800'}`}>{agency.status}</span></Link>)}{filtered.length === 0 && <p className="p-8 text-center text-slate-500">No agencies match these filters.</p>}</div></>;
}
