import Image from 'next/image';
import Link from 'next/link';
import PublicSiteShell from '@/components/PublicSiteShell';

export default function Home() {
  return <PublicSiteShell>
    <main>
      <section className="overflow-hidden bg-gradient-to-br from-[#071632] via-[#0b3f78] to-[#0795e6] px-5 py-20 text-white lg:py-28">
        <div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.1fr_.9fr] lg:px-3">
          <div><p className="text-sm font-bold uppercase tracking-[0.22em] text-sky-200">EMS operations, brought together</p><h1 className="mt-5 text-5xl font-black leading-[1.05] tracking-tight sm:text-7xl">Built for the people who keep EMS moving.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-blue-100">ApolloEMS brings scheduling, workforce management, timecards, certifications, operational reporting, and agency oversight into one purpose-built platform.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/contact" className="rounded-2xl bg-white px-6 py-4 font-bold text-[#0b3f78] shadow-xl hover:bg-sky-50">Request a Demo</Link><Link href="/features" className="rounded-2xl border border-white/35 px-6 py-4 font-bold hover:bg-white/10">Explore the Platform</Link></div></div>
          <div className="rounded-[2rem] border border-white/20 bg-white/10 p-6 shadow-2xl backdrop-blur"><div className="rounded-[1.5rem] bg-white p-8"><Image src="/apollo-logo.png" alt="Apollo EMS Management" width={600} height={600} priority className="mx-auto h-auto w-full max-w-md" /></div><p className="mt-5 text-center text-sm font-semibold text-blue-100">Built by EMS professionals for EMS professionals.</p></div>
        </div>
      </section>
      <section className="px-5 py-20"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="font-bold uppercase tracking-widest text-blue-700">One connected platform</p><h2 className="mt-3 text-4xl font-black tracking-tight">Less administrative friction. More operational clarity.</h2><p className="mt-5 text-lg leading-8 text-slate-600">ApolloEMS started as a scheduling application and is growing into a complete EMS operations platform—designed around the workflows agencies actually use.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{[
        ['Scheduling & staffing','Build schedules, identify open positions, and manage vacation requests.'],['Timecards & payroll review','Give employees and supervisors a clearer path from shift activity to review.'],['Employee records','Organize profiles, credentials, certifications, and renewal visibility.'],['Operational reporting','Bring inspections, incident reports, inventory, and supervisor workflows together.'],['Notifications','Keep personnel informed with agency announcements and operational alerts.'],['ePCR private beta','Protocol-informed documentation tools now being evaluated in EMS education.']
      ].map(([t,d])=><div key={t} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><h3 className="text-xl font-bold">{t}</h3><p className="mt-3 leading-7 text-slate-600">{d}</p></div>)}</div></div></section>
      <section className="bg-white px-5 py-20"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2"><div><p className="font-bold uppercase tracking-widest text-blue-700">ePCR private beta</p><h2 className="mt-3 text-4xl font-black tracking-tight">Training tomorrow’s EMS clinicians.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Merced College’s EMS Training Program is ApolloEMS’s first external ePCR beta organization, using the training environment to practice structured, protocol-informed documentation with simulated cases.</p><p className="mt-4 text-sm font-semibold text-slate-500">The beta environment is for education and simulated documentation—not live patient care.</p></div><div className="rounded-3xl bg-[#071632] p-8 text-white"><p className="text-2xl font-bold">Private beta program</p><ul className="mt-6 space-y-4 text-blue-100"><li>✓ EMS education-focused implementation</li><li>✓ Simulated patient documentation</li><li>✓ Instructor and student feedback</li><li>✓ Protocol-reference development</li></ul><Link href="/epcr-beta" className="mt-8 inline-block rounded-xl bg-sky-500 px-5 py-3 font-bold">Learn about ePCR Beta</Link></div></div></section>
      <section className="px-5 py-20"><div className="mx-auto max-w-5xl rounded-[2rem] bg-gradient-to-r from-[#0b1f4d] to-[#0878d1] p-10 text-center text-white sm:p-16"><h2 className="text-4xl font-black">Let’s build a better workflow for your agency.</h2><p className="mx-auto mt-5 max-w-2xl text-lg text-blue-100">Tell us how your organization operates and where administrative work slows your team down.</p><Link href="/contact" className="mt-8 inline-block rounded-2xl bg-white px-6 py-4 font-bold text-blue-800">Request a Conversation</Link></div></section>
    </main>
  </PublicSiteShell>;
}
