import type { AssessmentFindingOption } from './types';

export const assessmentFindingOptions: AssessmentFindingOption[] = [
  {
    id: 'airway-patent',
    label: 'Airway patent',
    type: 'positive',
    bodySystem: 'Airway',
  },
  {
    id: 'no-airway-obstruction',
    label: 'No obvious airway obstruction',
    type: 'pertinent-negative',
    bodySystem: 'Airway',
  },
  {
    id: 'breathing-unlabored',
    label: 'Breathing unlabored',
    type: 'positive',
    bodySystem: 'Respiratory',
  },
  {
    id: 'no-respiratory-distress',
    label: 'No respiratory distress noted',
    type: 'pertinent-negative',
    bodySystem: 'Respiratory',
    categories: ['Respiratory', 'Cardiovascular'],
  },
  {
    id: 'clear-lung-sounds',
    label: 'Lung sounds clear bilaterally',
    type: 'positive',
    bodySystem: 'Respiratory',
    categories: ['Respiratory', 'Cardiovascular'],
  },
  {
    id: 'no-jvd',
    label: 'No jugular venous distention noted',
    type: 'pertinent-negative',
    bodySystem: 'Cardiovascular',
    categories: ['Cardiovascular'],
  },
  {
    id: 'equal-radial-pulses',
    label: 'Radial pulses equal bilaterally',
    type: 'positive',
    bodySystem: 'Cardiovascular',
    categories: ['Cardiovascular'],
  },
  {
    id: 'no-peripheral-edema',
    label: 'No peripheral edema noted',
    type: 'pertinent-negative',
    bodySystem: 'Cardiovascular',
    categories: ['Cardiovascular'],
  },
  {
    id: 'skin-warm-dry',
    label: 'Skin warm and dry',
    type: 'positive',
    bodySystem: 'Skin',
    categories: ['Cardiovascular', 'Respiratory', 'Neurological'],
  },
  {
    id: 'no-facial-droop',
    label: 'No facial droop noted',
    type: 'pertinent-negative',
    bodySystem: 'Neurological',
    categories: ['Neurological'],
  },
  {
    id: 'no-arm-drift',
    label: 'No arm drift noted',
    type: 'pertinent-negative',
    bodySystem: 'Neurological',
    categories: ['Neurological'],
  },
  {
    id: 'speech-clear',
    label: 'Speech clear',
    type: 'positive',
    bodySystem: 'Neurological',
    categories: ['Neurological'],
  },
  {
    id: 'no-cspine-tenderness',
    label: 'No cervical spine tenderness noted',
    type: 'pertinent-negative',
    bodySystem: 'Trauma',
    categories: ['Injury', 'Musculoskeletal'],
  },
  {
    id: 'pms-intact',
    label: 'PMS intact distal to affected extremity',
    type: 'positive',
    bodySystem: 'Musculoskeletal',
    categories: ['Injury', 'Musculoskeletal'],
  },
  {
    id: 'no-obvious-deformity',
    label: 'No obvious deformity noted',
    type: 'pertinent-negative',
    bodySystem: 'Musculoskeletal',
    categories: ['Injury', 'Musculoskeletal'],
  },
];
