'use client';
export type ApgarAssessmentForm={assessedAt:string;appearance:string;pulse:string;grimace:string;activity:string;respiration:string;notes:string};
type Props={value:ApgarAssessmentForm;onChange:(field:keyof ApgarAssessmentForm,value:string)=>void};
const criteria:{field:keyof ApgarAssessmentForm;label:string;options:[string,string][]}[]=[
{field:'appearance',label:'Appearance / Skin Color',options:[['0','Blue or pale all over'],['1','Body pink; extremities blue'],['2','Completely pink']]},
{field:'pulse',label:'Pulse / Heart Rate',options:[['0','Absent'],['1','Below 100 bpm'],['2','100 bpm or greater']]},
{field:'grimace',label:'Grimace / Reflex Irritability',options:[['0','No response'],['1','Grimace or weak response'],['2','Cry, cough, sneeze, or withdrawal']]},
{field:'activity',label:'Activity / Muscle Tone',options:[['0','Limp'],['1','Some flexion'],['2','Active motion']]},
{field:'respiration',label:'Respiration',options:[['0','Absent'],['1','Slow or irregular; weak cry'],['2','Good respirations; strong cry']]},
];
export default function ApgarAssessmentCard({value,onChange}:Props){const selected=criteria.map(c=>value[c.field]).filter(Boolean);const score=selected.reduce((n,v)=>n+Number(v),0);const interpretation=selected.length<5?'Incomplete':score>=7?'Generally reassuring':score>=4?'Moderately depressed':'Severely depressed';return <div className="space-y-5"><div className="rounded-xl border border-slate-300 bg-slate-50 p-4"><div className="text-xs font-bold uppercase text-slate-500">APGAR Score</div><div className="mt-1 text-4xl font-black text-slate-900">{selected.length===5?score:'—'}<span className="text-lg text-slate-500"> / 10</span></div><p className="mt-1 text-sm font-semibold text-slate-600">{interpretation}</p></div><label className="block"><span className="mb-1 block text-sm font-semibold text-slate-700">Assessment Time</span><input type="datetime-local" value={value.assessedAt} onChange={e=>onChange('assessedAt',e.target.value)} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-slate-900"/></label>{criteria.map(c=><div key={c.field} className="rounded-xl border border-slate-200 p-4"><div className="mb-3 text-sm font-bold text-slate-800">{c.label}</div><div className="grid gap-2 md:grid-cols-3">{c.options.map(([points,text])=><button key={points} type="button" onClick={()=>onChange(c.field,points)} className={`rounded-lg border px-3 py-3 text-left text-sm font-semibold ${value[c.field]===points?'border-slate-900 bg-slate-900 text-white':'border-slate-300 bg-white text-slate-800'}`}><span className="block text-lg font-black">{points}</span>{text}</button>)}</div></div>)}<label className="block"><span className="mb-1 block text-sm font-semibold text-slate-700">Additional Notes (Optional)</span><textarea rows={3} value={value.notes} onChange={e=>onChange('notes',e.target.value)} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-slate-900"/></label></div>}
