import { createClinicalFactRegistry } from './clinicalFactRegistry';
import type { ClinicalFactDefinition } from './types';

/**
 * Stable Assessment fact definitions recognized by Apollo Clinical
 * Intelligence.
 *
 * These definitions describe clinical concepts only. They do not contain
 * patient data and do not read directly from AssessmentForm.
 *
 * Fact IDs are permanent integration identifiers. Display labels and
 * descriptions may be improved later, but an existing ID should not be
 * renamed once downstream rules begin using it.
 */
export const assessmentClinicalFactDefinitions = [
  {
    id: 'assessment.primary.general-impression',
    label: 'General Impression',
    source: 'assessment',
    category: 'primary-survey',
    valueType: 'string',
    description: 'Overall patient appearance on first contact.',
  },
  {
    id: 'assessment.primary.airway',
    label: 'Airway',
    source: 'assessment',
    category: 'primary-survey',
    valueType: 'string',
    description: 'Initial airway status and patency.',
  },
  {
    id: 'assessment.primary.breathing',
    label: 'Breathing',
    source: 'assessment',
    category: 'primary-survey',
    valueType: 'string',
    description: 'Initial breathing adequacy.',
  },
  {
    id: 'assessment.primary.circulation',
    label: 'Circulation',
    source: 'assessment',
    category: 'primary-survey',
    valueType: 'string',
    description: 'Initial circulation and immediate perfusion status.',
  },
  {
    id: 'assessment.primary.disability',
    label: 'Disability',
    source: 'assessment',
    category: 'primary-survey',
    valueType: 'string',
    description: 'Immediate neurological disability finding.',
  },
  {
    id: 'assessment.primary.exposure',
    label: 'Exposure',
    source: 'assessment',
    category: 'primary-survey',
    valueType: 'string',
    description: 'Immediate findings identified during patient exposure.',
  },

  {
    id: 'assessment.consciousness.avpu',
    label: 'AVPU',
    source: 'assessment',
    category: 'consciousness',
    valueType: 'string',
    description: 'Alert, verbal, painful, or unresponsive status.',
  },
  {
    id: 'assessment.consciousness.orientation',
    label: 'Orientation',
    source: 'assessment',
    category: 'consciousness',
    valueType: 'string',
    description: 'Documented patient orientation.',
  },

  {
    id: 'assessment.gcs.eyes',
    label: 'GCS Eye Response',
    source: 'assessment',
    category: 'gcs',
    valueType: 'number',
    description: 'Glasgow Coma Scale eye-opening score.',
    unit: 'points',
  },
  {
    id: 'assessment.gcs.verbal',
    label: 'GCS Verbal Response',
    source: 'assessment',
    category: 'gcs',
    valueType: 'number',
    description: 'Glasgow Coma Scale verbal-response score.',
    unit: 'points',
  },
  {
    id: 'assessment.gcs.motor',
    label: 'GCS Motor Response',
    source: 'assessment',
    category: 'gcs',
    valueType: 'number',
    description: 'Glasgow Coma Scale motor-response score.',
    unit: 'points',
  },
  {
    id: 'assessment.gcs.total',
    label: 'GCS Total',
    source: 'assessment',
    category: 'gcs',
    valueType: 'number',
    description: 'Calculated total Glasgow Coma Scale score.',
    unit: 'points',
  },

  {
    id: 'assessment.gfast.gaze',
    label: 'GFAST Gaze',
    source: 'assessment',
    category: 'stroke',
    valueType: 'string',
    description: 'Gaze finding documented during the GFAST stroke screen.',
  },
  {
    id: 'assessment.gfast.face',
    label: 'GFAST Facial Droop',
    source: 'assessment',
    category: 'stroke',
    valueType: 'string',
    description: 'Facial symmetry finding during the GFAST stroke screen.',
  },
  {
    id: 'assessment.gfast.arms',
    label: 'GFAST Arm Drift',
    source: 'assessment',
    category: 'stroke',
    valueType: 'string',
    description: 'Arm-drift finding during the GFAST stroke screen.',
  },
  {
    id: 'assessment.gfast.speech',
    label: 'GFAST Speech',
    source: 'assessment',
    category: 'stroke',
    valueType: 'string',
    description: 'Speech finding during the GFAST stroke screen.',
  },
  {
    id: 'assessment.gfast.last-known-well',
    label: 'Last Known Well',
    source: 'assessment',
    category: 'stroke',
    valueType: 'string',
    description: 'Time the patient was last known to be neurologically normal.',
  },
  {
    id: 'assessment.gfast.blood-glucose',
    label: 'Stroke Screen Blood Glucose',
    source: 'assessment',
    category: 'stroke',
    valueType: 'number',
    description: 'Blood glucose documented with the stroke assessment.',
    unit: 'mg/dL',
  },
  {
    id: 'assessment.gfast.score',
    label: 'GFAST Score',
    source: 'assessment',
    category: 'stroke',
    valueType: 'number',
    description: 'Calculated GFAST stroke-screen score.',
    unit: 'points',
  },

  {
    id: 'assessment.pain.present',
    label: 'Pain Present',
    source: 'assessment',
    category: 'pain',
    valueType: 'string',
    description: 'Whether the patient reports or demonstrates pain.',
  },
  {
    id: 'assessment.pain.scale-type',
    label: 'Pain Scale Type',
    source: 'assessment',
    category: 'pain',
    valueType: 'string',
    description: 'Pain scale used for the assessment.',
  },
  {
    id: 'assessment.pain.score',
    label: 'Pain Score',
    source: 'assessment',
    category: 'pain',
    valueType: 'number',
    description: 'Documented pain severity.',
    unit: '0-10',
  },
  {
    id: 'assessment.pain.onset',
    label: 'Pain Onset',
    source: 'assessment',
    category: 'pain',
    valueType: 'string',
    description: 'OPQRST onset description.',
  },
  {
    id: 'assessment.pain.provocation-palliation',
    label: 'Pain Provocation or Palliation',
    source: 'assessment',
    category: 'pain',
    valueType: 'string',
    description: 'Factors that provoke or relieve the pain.',
  },
  {
    id: 'assessment.pain.quality',
    label: 'Pain Quality',
    source: 'assessment',
    category: 'pain',
    valueType: 'string',
    description: 'Patient description of pain quality.',
  },
  {
    id: 'assessment.pain.radiation',
    label: 'Pain Radiation',
    source: 'assessment',
    category: 'pain',
    valueType: 'string',
    description: 'Location or pattern of pain radiation.',
  },
  {
    id: 'assessment.pain.time',
    label: 'Pain Time or Duration',
    source: 'assessment',
    category: 'pain',
    valueType: 'string',
    description: 'Timing or duration of the pain complaint.',
  },

  {
    id: 'assessment.respiratory.effort',
    label: 'Respiratory Effort',
    source: 'assessment',
    category: 'respiratory',
    valueType: 'string',
    description: 'Observed respiratory effort.',
  },
  {
    id: 'assessment.respiratory.airway-patency',
    label: 'Respiratory Airway Patency',
    source: 'assessment',
    category: 'respiratory',
    valueType: 'string',
    description: 'Airway patency documented during the respiratory assessment.',
  },
  {
    id: 'assessment.respiratory.breath-sounds-left',
    label: 'Left Breath Sounds',
    source: 'assessment',
    category: 'respiratory',
    valueType: 'string',
    description: 'Breath sounds documented on the left.',
  },
  {
    id: 'assessment.respiratory.breath-sounds-right',
    label: 'Right Breath Sounds',
    source: 'assessment',
    category: 'respiratory',
    valueType: 'string',
    description: 'Breath sounds documented on the right.',
  },
  {
    id: 'assessment.respiratory.accessory-muscle-use',
    label: 'Accessory Muscle Use',
    source: 'assessment',
    category: 'respiratory',
    valueType: 'string',
    description: 'Observed accessory-muscle use.',
  },
  {
    id: 'assessment.respiratory.current-support',
    label: 'Current Respiratory Support',
    source: 'assessment',
    category: 'respiratory',
    valueType: 'string',
    description: 'Respiratory support present during assessment.',
  },
  {
    id: 'assessment.respiratory.response',
    label: 'Observed Respiratory Response',
    source: 'assessment',
    category: 'respiratory',
    valueType: 'string',
    description: 'Observed response during the respiratory assessment.',
  },

  {
    id: 'assessment.aloc.current-mental-status',
    label: 'Current Mental Status',
    source: 'assessment',
    category: 'altered-consciousness',
    valueType: 'string',
    description: 'Current mental status documented during the ALOC assessment.',
  },
  {
    id: 'assessment.aloc.orientation',
    label: 'ALOC Orientation',
    source: 'assessment',
    category: 'altered-consciousness',
    valueType: 'string',
    description: 'Orientation documented during the ALOC assessment.',
  },
  {
    id: 'assessment.aloc.speech',
    label: 'ALOC Speech',
    source: 'assessment',
    category: 'altered-consciousness',
    valueType: 'string',
    description: 'Speech finding documented during the ALOC assessment.',
  },
  {
    id: 'assessment.aloc.pupils',
    label: 'ALOC Pupils',
    source: 'assessment',
    category: 'altered-consciousness',
    valueType: 'string',
    description: 'Pupil finding documented during the ALOC assessment.',
  },
  {
    id: 'assessment.aloc.blood-glucose',
    label: 'ALOC Blood Glucose',
    source: 'assessment',
    category: 'altered-consciousness',
    valueType: 'number',
    description: 'Blood glucose documented during the ALOC assessment.',
    unit: 'mg/dL',
  },
  {
    id: 'assessment.aloc.possible-causes',
    label: 'Possible ALOC Causes',
    source: 'assessment',
    category: 'altered-consciousness',
    valueType: 'string-list',
    description: 'Documented possible causes considered for altered consciousness.',
  },

  {
    id: 'assessment.ecg.not-indicated',
    label: 'ECG Not Indicated',
    source: 'assessment',
    category: 'cardiac',
    valueType: 'boolean',
    description: 'Whether an ECG was documented as not indicated.',
  },
  {
    id: 'assessment.ecg.four-lead-interpretation',
    label: 'Four-Lead ECG Interpretation',
    source: 'assessment',
    category: 'cardiac',
    valueType: 'string',
    description: 'Documented four-lead ECG interpretation.',
  },
  {
    id: 'assessment.ecg.twelve-lead-interpretation',
    label: 'Twelve-Lead ECG Interpretation',
    source: 'assessment',
    category: 'cardiac',
    valueType: 'string',
    description: 'Documented twelve-lead ECG interpretation.',
  },
  {
    id: 'assessment.ecg.abnormal-findings',
    label: 'ECG Abnormal Findings',
    source: 'assessment',
    category: 'cardiac',
    valueType: 'string',
    description: 'Additional abnormal ECG findings.',
  },

  {
    id: 'assessment.body.regions-assessed',
    label: 'Body Regions Assessed',
    source: 'assessment',
    category: 'physical-assessment',
    valueType: 'string-list',
    description: 'Body regions addressed during the physical assessment.',
  },
  {
    id: 'assessment.body.unremarkable-regions',
    label: 'Unremarkable Body Regions',
    source: 'assessment',
    category: 'physical-assessment',
    valueType: 'string-list',
    description: 'Body regions documented as unremarkable.',
  },
  {
    id: 'assessment.body.abnormal-regions',
    label: 'Abnormal Body Regions',
    source: 'assessment',
    category: 'physical-assessment',
    valueType: 'string-list',
    description: 'Body regions containing one or more abnormal findings.',
  },
  {
    id: 'assessment.body.dcap-btls-findings',
    label: 'DCAP-BTLS Findings',
    source: 'assessment',
    category: 'physical-assessment',
    valueType: 'string-list',
    description: 'Documented traumatic findings by body region or subregion.',
  },
  {
    id: 'assessment.body.cms-tp-findings',
    label: 'CMS-TP Findings',
    source: 'assessment',
    category: 'physical-assessment',
    valueType: 'string-list',
    description: 'Documented circulation, motor, sensation, tenderness, pulse, skin, and capillary-refill findings.',
  },
  {
    id: 'assessment.body.notes',
    label: 'Physical Assessment Notes',
    source: 'assessment',
    category: 'physical-assessment',
    valueType: 'string-list',
    description: 'Clinician-entered physical-assessment notes associated with body regions or subregions.',
  },
] as const satisfies readonly ClinicalFactDefinition[];

/**
 * Registry containing the Assessment facts currently recognized by Apollo.
 *
 * A later extractor patch will translate AssessmentForm values into
 * patient-specific ClinicalFact records validated by this registry.
 */
export const assessmentClinicalFactRegistry = createClinicalFactRegistry(
  assessmentClinicalFactDefinitions,
);