export type CallForm = {
  emsResponseNumber: string;
  emsIncidentNumber: string;
  dispatchedPriority: string;
  respondingUnitNumber: string;
  respondingCrew: string;
  pcrDocumentedBy: string;
  dispatchedNatureOfCall: string;
  typeOfServiceRequested: string;
  responseModeToScene: string;
  incidentLocationType: string;
  incidentLocationTypeOther: string;
  incidentStreet: string;
  incidentApartment: string;
  incidentCity: string;
  incidentZip: string;
  numberOfPatientsAtScene: string;
  firstEmsUnitOnScene: string;
  otherAgenciesMode: 'None' | 'Add';
  otherAgenciesOnScene: string;
  hazardousHealthExposures: string;
  hazardousHealthExposuresOther: string;
  personalProtectiveEquipmentUsed: string[];
  personalProtectiveEquipmentOther: string;
  callReceived: string;
  callDispatched: string;
  unitEnRoute: string;
  unitOnScene: string;
  patientContact: string;
  departScene: string;
  arrivedAtDestination: string;
  transferOfCare: string;
  unitBackInService: string;
};

export type PatientForm = {
  firstName: string;
  middleInitial: string;
  lastName: string;
  unablePatientName: boolean;
  dateOfBirth: string;
  unableDateOfBirth: boolean;
  unableAge: boolean;
  patientStreet: string;
  patientApartment: string;
  patientCity: string;
  patientZip: string;
  unablePatientAddress: boolean;
  gender: string;
  unableGender: boolean;
  phoneNumber: string;
  unablePhoneNumber: boolean;
  socialSecurityNumber: string;
  unableSocialSecurityNumber: boolean;
  race: string;
  unableRace: boolean;
  medicalHistory: string;
  surgicalHistory: string;
  currentMedications: string;
  lastOralIntake: string;
  medicationAllergies: string;
  environmentalAllergies: string;
  patientEffects: string;
  patientEffectsLeftWith: string;
  patientEffectsLeftWithOther: string;
  disposition: string;
  dispositionExplanation: string;
};

export type CodedSelection = {
  code: string;
  description: string;
};

export type ComplaintForm = {
  clinicalCategory: string;
  primaryImpression: CodedSelection | null;
  secondaryImpression: CodedSelection | null;
  emsConditionCode: CodedSelection | null;
  primarySymptom: CodedSelection | null;
  otherAssociatedSymptoms: CodedSelection[];
  symptomsBeganDateTime: string;
  lastSeenNormalDateTime: string;
  patientAcuity: string;
  possibleInjuryTrauma: string;
  cardiacArrest: string;
  suspectedStrokeCva: string;
  strokeCvaSymptomsResolved: string;
  patientPlacedOn5150Hold: string;
  possibleDrugAlcoholUse: string;
  drugAlcoholIndications: string[];
  suspectedDrug: string;
  workRelatedIllnessInjury: string;
};
