export type CallForm = {
  emsResponseNumber: string;
  dispatchedPriority: string;
  respondingUnitNumber: string;
  respondingCrew: string;
  pcrDocumentedBy: string;
  dispatchedNatureOfCall: string;
  typeOfServiceRequested: string;
  responseModeToScene: string;
  incidentLocationType: string;
  incidentLocationTypeOther: string;
  incidentStreet: string;
  incidentApartment: string;
  incidentCity: string;
  incidentZip: string;
  numberOfPatientsAtScene: string;
  firstEmsUnitOnScene: string;
  otherAgenciesMode: 'None' | 'Add';
  otherAgenciesOnScene: string;
  hazardousHealthExposures: string;
  hazardousHealthExposuresOther: string;
  personalProtectiveEquipmentUsed: string[];
  personalProtectiveEquipmentOther: string;
  callReceived: string;
  callDispatched: string;
  unitEnRoute: string;
  unitOnScene: string;
  patientContact: string;
  departScene: string;
  arrivedAtDestination: string;
  transferOfCare: string;
  unitBackInService: string;
};
