import type { ProtocolPack } from "../../types";

export const ccemsaProtocolPack: ProtocolPack = {
  id: "apollo-protocol-catalog",
  displayName: "Apollo EMS Protocol Catalog",
  version: "2026",
  protocols: [
    {
      id: "merced-700",
      number: "700",
      title: "General Procedures",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20700%20General%20Procedures%20-%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-702",
      number: "702",
      title: "Cardiac Arrest",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20702%20Cardiac%20Arrest%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-704",
      number: "704",
      title: "Chest Pain",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20704%20Chest%20Pain%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-706",
      number: "706",
      title: "Bradycardia",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20706%20Bradycardia%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-708",
      number: "708",
      title: "Tachyarrhythmias",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20708%20Tachyarrhythmias%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-710",
      number: "710",
      title: "ROSC",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20710%20ROSC%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-712",
      number: "712",
      title: "Airway Obstruction",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20712%20Airway%20Obstruction%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-714",
      number: "714",
      title: "Respiratory Distress",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20714%20Respiratory%20Distress%20New%20Format%20-%20Final%20-%2011.2025%20-%20Revision%20-%203.5.2026.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-716",
      number: "716",
      title: "Nausea And Vomiting",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20716%20Nausea%20and%20Vomiting%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-718",
      number: "718",
      title: "Pain Management",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20718%20Pain%20Management%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-720",
      number: "720",
      title: "Sepsis",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20720%20Sepsis%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-722",
      number: "722",
      title: "Stroke",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20722%20Stroke%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-724",
      number: "724",
      title: "Altered Level Of Consciousness (aloc) Or Syncope",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20724%20Altered%20Level%20of%20Consciousness%20(ALOC)%20or%20Syncope%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-726",
      number: "726",
      title: "Allergic Reaction And Anaphylactic Shock",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20726%20Allergic%20Reaction%20and%20Anaphylactic%20Shock%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-728",
      number: "728",
      title: "Seizures",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20728%20Seizures%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-730",
      number: "730",
      title: "Hyperglycemia",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20730%20Hyperglycemia%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-732",
      number: "732",
      title: "Hyperthermia",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20732%20Hyperthermia%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-734",
      number: "734",
      title: "Hypothermia",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20734%20Hypothermia%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-736",
      number: "736",
      title: "Medication Poisonings",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20736%20Medication%20Poisonings%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-738",
      number: "738",
      title: "Non-traumatic Shock",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20738%20Non-Traumatic%20Shock%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-740",
      number: "740",
      title: "Dystonic Reactions",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20740%20Dystonic%20Reactions%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-742",
      number: "742",
      title: "Behavioral Emergency",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20742%20Behavioral%20Emergency%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-744",
      number: "744",
      title: "Envenomation-bites-stings",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20744%20Envenomation-Bites-Stings%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-746",
      number: "746",
      title: "Organophosphates Exposure",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20746%20Organophosphates%20Exposure%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-748",
      number: "748",
      title: "Ob-gyb Emergencies",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20748%20OB-GYB%20Emergencies%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-749",
      number: "749",
      title: "Newborn Resuscitation",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20749%20Newborn%20Resuscitation%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-750",
      number: "750",
      title: "Spinal Motion Restriction",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20750%20Spinal%20Motion%20Restriction%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-752",
      number: "752",
      title: "Trauma",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20752%20Trauma%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-754",
      number: "754",
      title: "Traumatic Arrest",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20754%20Traumatic%20Arrest%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-756",
      number: "756",
      title: "Burns",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20756%20Burns%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-758",
      number: "758",
      title: "TXA Bleeding Control",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20758%20TXA%20-%20Bleeding%20Control%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-760",
      number: "760",
      title: "Airway Management",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20760%20Airway%20Management%20New%20Format%20-%20Final%20-%2011.2025.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-910",
      number: "910",
      title: "Multiple Casualty Incident (mci) Field Operations",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20910%20-%20Multiple%20Casualty%20Incident%20(MCI)%20-%20Field%20Operations.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-915",
      number: "915",
      title: "Hazardous Materials Incidents",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20915%20-%20%20Hazardous%20Materials%20Incidents.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "merced-920",
      number: "920",
      title: "Nerve Agent Exposures",
      category: "Merced County",
      revision: "",
      pdf: "/protocols/merced-county/EMS%20Policy%20920%20-%20Nerve%20Agent%20Exposures%20-%207.2024%20-%20Revision%203.5.2026.pdf",
      source: "Merced County EMS",
      level: "All",
    },
    {
      id: "ccemsa-bls-510-02",
      number: "510.02",
      title: "Basic Life Support Call Ins",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-02-basic-life-support-call-ins.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-03",
      number: "510.03",
      title: "Prehospital Rendezvous",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-03-prehospital-rendezvous.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-04",
      number: "510.04",
      title: "Prehospital Use Of Oxygen",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-04-prehospital-use-of-oxygen.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-05",
      number: "510.05",
      title: "Tracheostomy Care Suctioning",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-05-tracheostomy-care-suctioning.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-07",
      number: "510.07",
      title: "Monitoring Ivs",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-07-monitoring-ivs.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-09",
      number: "510.09",
      title: "Cardiac Arrest Trauma",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-09-cardiac-arrest-trauma.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-10",
      number: "510.10",
      title: "Chest Pain",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-10-chest-pain.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-11",
      number: "510.11",
      title: "Respiratory Distress",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-11-respiratory-distress.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-12",
      number: "510.12",
      title: "Airway Obstruction",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-12-airway-obstruction.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-14",
      number: "510.14",
      title: "Syncope Any Transient Loss Of Consciousness",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-14-syncope-any-transient-loss-of-consciousness.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-15",
      number: "510.15",
      title: "Seizures",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-15-seizures.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-17",
      number: "510.17",
      title: "Ingestion Poisoning",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-17-ingestion-poisoning.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-18",
      number: "510.18",
      title: "Abdominal Emergencies Medical And Trauma",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-18-abdominal-emergencies-medical-and-trauma.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-19",
      number: "510.19",
      title: "Shock Hypotension",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-19-shock-hypotension.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-20",
      number: "510.20",
      title: "Head Trauma",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-20-head-trauma.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-21",
      number: "510.21",
      title: "Chest Trauma",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-21-chest-trauma.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-22",
      number: "510.22",
      title: "Orthopedic Trauma",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-22-orthopedic-trauma.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-23",
      number: "510.23",
      title: "Soft Tissue Injuries",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-23-soft-tissue-injuries.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-24",
      number: "510.24",
      title: "Ear Injuries",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-24-ear-injuries.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-25",
      number: "510.25",
      title: "Eye Injuries",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-25-eye-injuries.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-26",
      number: "510.26",
      title: "Burns",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-26-burns.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-27",
      number: "510.27",
      title: "Hyperthermia",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-27-hyperthermia.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-28",
      number: "510.28",
      title: "Hypothermia",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-28-hypothermia.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-29",
      number: "510.29",
      title: "Frostbite",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-29-frostbite.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-30",
      number: "510.30",
      title: "Near Drowning",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-30-near-drowning.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-33",
      number: "510.33",
      title: "Childbirth Protocol",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-33-childbirth-protocol.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-34",
      number: "510.34",
      title: "Behavioral Emergencies",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-34-behavioral-emergencies.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510",
      number: "510",
      title: "BLS Policy",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510-a.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-01",
      number: "510.01",
      title: "Table Of Contents",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510.01_table-of-contents-b.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-06",
      number: "510.06",
      title: "Spinal Motion Restriction",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510.06_spinal-motion-restriction-a.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-08",
      number: "510.08",
      title: "Cardiac Arrest Medical BLS",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510.08_cardiac-arrest_medical-bls-b.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-13",
      number: "510.13",
      title: "Altered Ms And Syncope",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510.13-altered-ms-and-syncope.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-16",
      number: "510.16",
      title: "Stroke",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510.16-stroke.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-31",
      number: "510.31",
      title: "Snakebite",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510.31_snakebite.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-32",
      number: "510.32",
      title: "Allergic Reactions And Anaphylaxis",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510.32_allergic-reactions-and-anaphylaxis.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-35",
      number: "510.35",
      title: "BLS Pediatric Respiratory Distress",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510.35-bls-pediatric-respiratory-distress.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-36",
      number: "510.36",
      title: "Pediatric Arrest Medical",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510.36-pediatric-arrest-medical.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-bls-510-37",
      number: "510.37",
      title: "Supraglottic Airway",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/bls/510.37_supraglottic-airway.pdf",
      source: "CCEMSA",
      level: "BLS",
    },
    {
      id: "ccemsa-als-530-07",
      number: "530.07",
      title: "Ventricular Tachycardia With Pulses",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530-07-ventricular-tachycardia-with-pulses.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-12",
      number: "530.12",
      title: "Atrial Fibrillation",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530-12-atrial-fibrillation.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-14",
      number: "530.14",
      title: "Shortness Of Breath With Bronchospasm Including COPD And Asthma",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530-14-shortness-of-breath-with-bronchospasm-including-copd-and-asthma.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-15",
      number: "530.15",
      title: "Shortness Of Breath With Pulmonary Edema Including Chf",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530-15-shortness-of-breath-with-pulmonary-edema-including-chf.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-16",
      number: "530.16",
      title: "Respiratory Distress",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530-16-respiratory-distress.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-17",
      number: "530.17",
      title: "Airway Obstruction Foreign Body",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530-17-airway-obstruction-foreign-body.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-19",
      number: "530.19",
      title: "Seizures",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530-19-seizures.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-20",
      number: "530.20",
      title: "Ingestion Poisoning",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530-20-ingestion-poisoning.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-21",
      number: "530.21",
      title: "Shock Non Traumatic",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530-21-shock-non-traumatic.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-25",
      number: "530.25",
      title: "Near Drowning",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530-25-near-drowning.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-27",
      number: "530.27",
      title: "Behavioral Emergencies",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530-27-behavioral-emergencies.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-28",
      number: "530.28",
      title: "Dystonic Reaction To Phenothiazine Drugs",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530-28-dystonic-reaction-to-phenothiazine-drugs.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-29",
      number: "530.29",
      title: "Vaginal Bleeding",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530-29-vaginal-bleeding.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-32",
      number: "530.32",
      title: "Pediatric Primary Survey",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530-32-pediatric-primary-survey.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-37",
      number: "530.37",
      title: "Pediatric Tachycardia With Pulses",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530-37-pediatric-tachycardia-with-pulses.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-39",
      number: "530.39",
      title: "Pediatric Shock Non Traumatic",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530-39-pediatric-shock-non-traumatic.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-41",
      number: "530.41",
      title: "Nausea And Or Vomiting",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530-41-nausea-and-or-vomiting.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530",
      number: "530",
      title: "A Policy",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530-a-policy.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-01",
      number: "530.01",
      title: "Table Of Contents",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.01_table-of-contents-c.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-02",
      number: "530.02",
      title: "General Procedures",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.02-general-procedures-g.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-04",
      number: "530.04",
      title: "Cardiac Arrest Medical",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.04_cardiac-arrest_medical-a.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-05",
      number: "530.05",
      title: "Cardiac Arrest Trauma",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.05_cardiac-arrest_trauma.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-06",
      number: "530.06",
      title: "Dysrhythmias",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.06_dysrhythmias.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-10",
      number: "530.10",
      title: "Bradydysrhythmias",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.10_bradydysrhythmias-a.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-11",
      number: "530.11",
      title: "Paroxysmal Supraventricular Tachycardia Pvst",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.11_paroxysmal-supraventricular-tachycardia-pvst.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-13",
      number: "530.13",
      title: "Coronary Ischemic Chest Discomfort",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.13-coronary-ischemic-chest-discomfort.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-18",
      number: "530.18",
      title: "Altered Ms And Syncope",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.18_altered-ms-and-syncope.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-22",
      number: "530.22",
      title: "Allergic Reactions And Anaphylactic Shock",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.22_allergic-reactions-and-anaphylactic-shock-a.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-23",
      number: "530.23",
      title: "Trauma",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.23_trauma-b.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-24",
      number: "530.24",
      title: "Burns",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.24_burns-a.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-26",
      number: "530.26",
      title: "Snakebite",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.26_snakebite-a.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-30",
      number: "530.30",
      title: "Childbirth",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.30_childbirth.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-31",
      number: "530.31",
      title: "Neonatal Resuscitation",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.31-neonatal-resuscitation-a.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-33",
      number: "530.33",
      title: "Pediatric Arrest Medical",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.33-pediatric-arrest-medical.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-36",
      number: "530.36",
      title: "Pediatric Bradycardia",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.36_pediatric-bradycardia-a.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-38",
      number: "530.38",
      title: "Pediatric Respiratory Distress",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.38-pediatric-respiratory-distress-a.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-40",
      number: "530.40",
      title: "Suspected Stroke",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.40-suspected-stroke.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-42",
      number: "530.42",
      title: "Adult Pain Management",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.42_adult-pain-management.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-43",
      number: "530.43",
      title: "Pediatric Pain Management",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.43_pediatric-pain-management.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-44",
      number: "530.44",
      title: "Ventilators Automatic Transport",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.44_ventilators-automatic-transport-a.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-530-45",
      number: "530.45",
      title: "Pediatric Allergic Reactions And Anaphylactic Shock",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/530.45_pediatric-allergic-reactions-and-anaphylactic-shock-a.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
    {
      id: "ccemsa-als-drug-box",
      number: "Drug Box",
      title: "Drug Box 01 26",
      category: "CCEMSA",
      revision: "",
      pdf: "/protocols/ccemsa/als/drug-box_01-26.pdf",
      source: "CCEMSA",
      level: "ALS",
    },
  ],
} as const;
